import React,{useEffect,useState} from "react";
import {Link} from "react-router-dom";
import {useFinanceDispatch,useFinanceState} from "../../context/FinanceContext.jsx";
import {Button,Card,Field,Input,Modal,Select,ProgressBar} from "../ui/primitives.jsx";
import {monthKey,monthlyPlanStatus} from "../../services/financial/monthlyPlan.js";
import {fmtBs} from "../../services/financial/format.js";
import {CategoryManager} from "./CategoryManager.jsx";

export function MonthlyPlanPanel({month,onMonth,requestEdit,onEditClosed}) {
  const state=useFinanceState(); const [editing,setEditing]=useState(false);
  const status=monthlyPlanStatus(state,month);
  useEffect(()=>{if(requestEdit) setEditing(true);},[requestEdit]);
  const cash=status.cash;
  const today=monthlyPlanStatus(state);
  const todayCash=today.cash;
  const fmt=value=>fmtBs(value,state.profile.currency);
  return <div className="flex flex-col gap-5"><Card title="Plan del mes" action={month >= monthKey() ? <Button size="sm" onClick={()=>setEditing(true)}>{status.plan ? "Editar plan" : "Crear plan"}</Button> : null}><Field label="Mes que quieres consultar"><Input type="month" value={month} onChange={e=>{if(e.target.value) onMonth(e.target.value);}} /></Field>
    {!status.plan ? <p className="mt-3 text-sm text-ink-soft">Estima los ingresos y gastos de todo el mes y el dinero que quieres conservar. Las estimaciones no crean movimientos.</p> : <><p className="mt-3 text-sm">Objetivo disponible al cierre: <strong>{fmt(status.target)}</strong>. {(status.plan.revisions || []).length ? "El plan fue modificado; cada categoría conserva su estimación original." : ""}</p><p className="text-xs text-ink-soft">Prioridad: {status.plan.priority || "Todavía no tengo una prioridad"}</p></>}
  </Card>
  <div className="grid sm:grid-cols-2 gap-4"><Card title="Dinero disponible hoy"><p className="font-display text-2xl">{fmt(today.plan ? today.availableToday : todayCash.spendable)}</p><p className="text-xs text-ink-soft mt-2">Dinero total {fmt(todayCash.total)} · cuentas de ahorro {fmt(todayCash.savings)} · protegido en cuentas de uso diario {fmt(todayCash.protectedMoney)}. No se suma nuevamente dinero vinculado a planes.</p><Link to="/cuentas" className="text-sm underline">Ver cuentas</Link></Card><Card title={status.historical ? "Disponible conciliado al cierre" : "Disponible estimado al cierre"}>{status.available ? <><p className="font-display text-2xl">{fmt(status.closing)}</p><p className="text-sm mt-2">{status.targetDifference >= 0 ? `Supera el objetivo en ${fmt(status.targetDifference)}` : `Faltan ${fmt(-status.targetDifference)} para el objetivo`}</p><p className="text-xs text-ink-soft">{status.startDate} a {status.endDate} · {status.days} días · confianza {status.confidence}</p><details className="mt-3 text-sm"><summary>Ver fórmula y supuestos</summary><ul className="mt-2 space-y-1"><li>{status.historical ? "Saldo conciliado de uso diario al cierre:" : "Disponible en cuentas de uso diario:"} {fmt(cash.spendable)}</li><li>+ Ingresos pendientes: {fmt(status.incomePending)}</li><li>− Fijos pendientes: {fmt(status.fixedPending)}</li><li>− Variables pendientes: {fmt(status.variablePending)}</li><li>− Cuotas no incluidas en fijos: {fmt(status.debtPending)}</li><li>− Compromisos de meses anteriores: {fmt(status.overduePending)}</li><li>− Aportes pendientes: {fmt(status.savingsPending)}</li></ul></details>{status.historical && status.closing>0 ? <p className="text-sm mt-3">Te quedaron {fmt(status.closing)} disponibles al cierre. <Link className="underline" to={`/movimientos?operacion=ahorro&monto=${Math.max(0,Math.min(status.closing,today.availableToday ?? today.cash.spendable))}`}>Elegir todo o parte para un plan de ahorro</Link>. También puedes conservarlo sin registrar una operación.</p> : null}{status.confidenceIssues.map(issue=><p key={issue} className="text-xs text-ochre mt-2">{issue}</p>)}</> : <p className="text-sm text-ink-soft">{status.missing.join(". ")}. {status.historical ? "Las estimaciones y los resultados operativos se conservan abajo; no reconstruimos un saldo sin evidencia." : "Crea tu Plan del mes para ver la fórmula."}</p>}</Card></div>
  {status.plan ? <><Card title="Estimado frente a real"><div className="overflow-x-auto"><table className="w-full text-xs text-left"><thead><tr>{["Categoría / compromiso","Estimado","Real","Pendiente","Diferencia"].map(label=><th key={label} className="p-2">{label}</th>)}</tr></thead><tbody>{[...status.incomes,...status.expenses].map(item=><tr key={item.id} className="border-t border-line"><th className="p-2 font-normal">{item.name || item.categorySnapshot?.name}<span className="block text-ink-soft">{item.categorySnapshot?.type === "ingreso" ? "Ingreso" : item.classification === "fijo" ? "Fijo" : "Variable"}{item.completed ? " · Pago completo" : ""}{item.originalEstimated !== item.estimated ? ` · Original ${fmt(item.originalEstimated)}` : ""}</span>{item.classification === "fijo" && !item.completed ? <Link className="underline" to={`/movimientos?nuevo=gasto&planMonth=${month}&planItemId=${item.id}&volver=/mi-mes`}>Registrar pago</Link> : null}</th><td className="p-2">{fmt(item.estimated)}</td><td className="p-2">{fmt(item.actual)}</td><td className="p-2">{fmt(item.pending)}</td><td className="p-2">{fmt(item.difference)}</td></tr>)}</tbody></table></div><Link className="text-sm underline mt-3 inline-block" to="/movimientos">Ver y registrar movimientos reales</Link></Card>
    <Card title="Límites variables"><div className="grid sm:grid-cols-2 gap-4">{status.expenses.filter(item=>item.classification === "variable").map(item=><div key={item.id} className="rounded border border-line p-3"><strong className="text-sm">{item.categorySnapshot.name}</strong><p className="text-xs mt-1">{fmt(item.actual)} de {fmt(item.estimated)} · {Number.isFinite(item.used) ? Math.round(item.used*100) : "Más de 100"}%</p><ProgressBar value={item.used*100} /><p className={`text-xs mt-2 ${item.alert ? "text-brick" : "text-ink-soft"}`}>{item.alert === "superado" ? `Ya gastaste ${fmt(item.actual)}: ${fmt(item.difference)} más de lo estimado. Podrían quedar gastos adicionales.` : item.alert === "alcanzado" ? `Alcanzaste el límite mensual de ${fmt(item.estimated)}.` : `Te quedan ${fmt(item.remaining)} dentro del límite.${item.alert === "cerca" ? " Estás cerca de alcanzarlo." : ""}`}</p><div className="flex gap-3 mt-2"><Link className="text-xs underline" to={`/movimientos?categoria=${item.categoryId}`}>Ver movimientos</Link><button className="text-xs underline" onClick={()=>setEditing(true)}>Revisar mi estimación</button></div></div>)}</div></Card>
    {status.overdue.length ? <Card title="Compromisos anteriores pendientes">{status.overdue.map(item=><div key={item.id} className="text-sm py-2"><span>{item.planMonth} · {item.name} · {fmt(item.pending)}</span><Link className="ml-2 underline" to={`/movimientos?nuevo=gasto&planMonth=${item.planMonth}&planItemId=${item.id.slice(8)}&volver=/mi-mes`}>Registrar pago</Link></div>)}</Card> : null}
  </> : null}
  <Modal open={editing} onClose={()=>{setEditing(false);onEditClosed?.();}} title="Configurar Plan del mes"><MonthlyPlanWizard month={month} onSaved={saved=>{onMonth(saved);setEditing(false);onEditClosed?.();}} /></Modal>
  </div>;
}

const PRIORITIES=["No terminar con las justas","Terminar con más dinero disponible","Avanzar en un plan de ahorro","Reducir el peso de mis cuotas","Estar mejor preparado para un imprevisto","Todavía no tengo una prioridad"];
function MonthlyPlanWizard({month,onSaved}) {
  const state=useFinanceState(); const dispatch=useFinanceDispatch();
  const old=state.monthlyPlans.find(plan=>plan.month === month);
  const [draft,setDraft]=useState(()=>old || {month:month < monthKey() ? monthKey() : month,incomes:[],expenses:[],savings:[],closingTarget:0,priority:PRIORITIES[5],recordsComplete:null,emergency:{status:"unknown",sourceType:"account",sourceId:"",amount:0}});
  const [step,setStep]=useState(1);const [error,setError]=useState("");const [working,setWorking]=useState(false);const [categoriesOpen,setCategoriesOpen]=useState(false);
  const update=(key,value)=>setDraft(current=>({...current,[key]:value}));
  const reference=monthlyPlanStatus({...state,monthlyPlans:[...state.monthlyPlans.filter(plan=>plan.month !== draft.month),draft]},draft.month);
  const fmt=value=>fmtBs(value,state.profile.currency);
  function rows(key,type,classification) {
    const categories=state.categories.filter(category=>category.type === type && !category.system && !category.archived && (!classification || category.classification === classification));
    const items=draft[key].filter(item=>!classification || item.classification === classification);
    const replace=(id,changes)=>update(key,draft[key].map(item=>item.id === id ? {...item,...changes} : item));
    const obligations=[...state.debts.filter(debt=>debt.balance>0).map(debt=>({id:debt.linkedAccountId || debt.id,name:debt.name})),...state.accounts.filter(account=>account.type === "tarjeta_credito" && account.balance<0).map(account=>({id:account.id,name:account.name}))];
    return <div className="flex flex-col gap-3">{items.map(item=><div key={item.id} className="border border-line rounded p-3 flex flex-col gap-2"><Field label="Categoría"><Select value={item.categoryId} onChange={e=>replace(item.id,{categoryId:e.target.value})}>{[...categories,...state.categories.filter(category=>category.id === item.categoryId && !categories.some(cat=>cat.id === category.id))].map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</Select></Field>{classification === "fijo" ? <><Field label="Nombre del compromiso"><Input required value={item.name} onChange={e=>replace(item.id,{name:e.target.value})} placeholder="Ej. Alquiler del departamento" /></Field><Field label="Cuota o tarjeta incluida (si corresponde)"><Select value={item.linkedObligationId || ""} onChange={e=>replace(item.id,{linkedObligationId:e.target.value || null})}><option value="">No corresponde</option>{obligations.filter((item,index,all)=>all.findIndex(other=>other.id === item.id) === index).map(debt=><option key={debt.id} value={debt.id}>{debt.name}</option>)}</Select></Field></> : null}<Field label={classification === "variable" ? "Estimación y límite mensual" : "Estimación de todo el mes"}><Input type="number" min="0" step="0.01" required value={item.estimated} onChange={e=>replace(item.id,{estimated:e.target.value})} /></Field><Button size="sm" variant="ghost" onClick={()=>update(key,draft[key].filter(row=>row.id !== item.id))}>Quitar {item.name || state.categories.find(category=>category.id === item.categoryId)?.name}</Button></div>)}<Button variant="secondary" disabled={!categories.length} onClick={()=>update(key,[...draft[key],{id:crypto.randomUUID(),categoryId:categories[0]?.id,name:classification === "fijo" ? categories[0]?.name : "",estimated:0,...(classification ? {classification} : {})}])}>Añadir {classification === "fijo" ? "compromiso fijo" : classification === "variable" ? "categoría variable" : "ingreso estimado"}</Button></div>;
  }
  async function save(){setWorking(true);setError("");try{if(draft.recordsComplete === null) throw new Error("Indica si tus movimientos incluyen todo el mes.");const result=await dispatch({type:"SAVE_MONTHLY_PLAN",payload:draft});if(result?.ok === false) throw new Error(result.error);onSaved(draft.month);}catch(error){setError(error.message);}finally{setWorking(false);}}
  return <div className="flex flex-col gap-4"><p className="text-xs text-ink-soft">Paso {step} de 5 · estimaciones, no movimientos</p>
    {step === 1 ? <><h3 className="font-semibold">¿Para qué mes quieres crear tu plan?</h3><Field label="Mes del plan"><Input type="month" min={old ? undefined : monthKey()} disabled={Boolean(old)} value={draft.month} onChange={e=>update("month",e.target.value)} required /></Field><p className="text-sm">Estima los ingresos y gastos de todo el mes, aunque lo estés configurando después de que haya comenzado.</p>{draft.month > monthKey() ? <p className="text-xs text-ochre">El saldo de apertura se actualizará cuando termine el mes anterior.</p> : null}{draft.recordsComplete === null || !old ? <Field label="¿Tus movimientos incluyen lo que ingresaste y gastaste desde el inicio del mes?"><Select value={draft.recordsComplete === null ? "" : String(draft.recordsComplete)} onChange={e=>update("recordsComplete",e.target.value === "" ? null : e.target.value === "true")}><option value="">Selecciona</option><option value="true">Sí, están completos</option><option value="false">No, me faltan registros</option></Select></Field> : <p className="text-xs">Registros {draft.recordsComplete ? "completos" : "pendientes de completar"}. <button className="underline" onClick={()=>update("recordsComplete",!draft.recordsComplete)}>Cambiar</button></p>}</> : null}
    {step === 2 ? <><h3 className="font-semibold">¿Cuánto dinero estimas recibir durante este mes?</h3><p className="text-sm">Ya registraste {fmt(reference.actualIncome)} en ingresos este mes. ¿Cuánto estimas recibir en total? Incluye ingresos ya recibidos.</p>{rows("incomes","ingreso")}</> : null}
    {step === 3 ? <><h3 className="font-semibold">¿Cuánto estimas gastar durante este mes?</h3><p className="text-sm">Ya registraste {fmt(reference.actualExpense)}. Incluye los gastos de todo el mes.</p><h4 className="font-medium">Gastos fijos</h4>{rows("expenses","gasto","fijo")}<h4 className="font-medium mt-2">Gastos variables</h4>{rows("expenses","gasto","variable")}</> : null}
    {step === 4 ? <><h3 className="font-semibold">¿Con cuánto dinero te gustaría terminar el mes?</h3><p className="text-sm">Es el dinero que quieres conservar disponible después de tus gastos y los aportes que decidas separar para tus planes de ahorro.</p><Field label="Monto disponible objetivo"><Input type="number" min="0" step="0.01" value={draft.closingTarget} onChange={e=>update("closingTarget",e.target.value)} /></Field><Button variant="secondary" onClick={()=>update("closingTarget",0)}>Sin un monto mínimo</Button><h4 className="font-medium">¿Quieres aportar a algún plan de ahorro este mes?</h4><Button variant="ghost" onClick={()=>update("savings",[])}>No, sin aportes previstos</Button>{state.goals.map(goal=><Field key={goal.id} label={`Aporte previsto — ${goal.name}`}><Input type="number" min="0" step="0.01" value={draft.savings.find(item=>item.goalId === goal.id)?.estimated ?? 0} onChange={e=>update("savings",[...draft.savings.filter(item=>item.goalId !== goal.id),{goalId:goal.id,estimated:e.target.value}])} /></Field>)}<p className="text-xs text-ink-soft">Puedes crear y administrar tus planes en Planes de Ahorro después de guardar esta configuración.</p></> : null}
    {step === 5 ? <><Field label="¿Qué te gustaría mejorar este mes?"><Select value={draft.priority} onChange={e=>update("priority",e.target.value)}>{PRIORITIES.map(priority=><option key={priority}>{priority}</option>)}</Select></Field><p className="text-xs text-ink-soft">Esta preferencia personaliza recomendaciones; no mejora el puntaje.</p><Field label="Si surge un gasto inesperado, ¿tienes ahorros que podrías utilizar?"><Select value={draft.emergency.status} onChange={e=>update("emergency",{...draft.emergency,status:e.target.value})}><option value="separate">Sí, tengo dinero separado para eso</option><option value="savings">Sí, podría usar parte de mis ahorros</option><option value="none">No tengo ahorros disponibles</option><option value="unknown">Prefiero no incluirlo por ahora</option></Select></Field>{["separate","savings"].includes(draft.emergency.status) ? <><Field label="Origen del ahorro disponible"><Select value={`${draft.emergency.sourceType}:${draft.emergency.sourceId}`} onChange={e=>{const [sourceType,sourceId]=e.target.value.split(":");update("emergency",{...draft.emergency,sourceType,sourceId});}}><option value="account:">Selecciona una cuenta o plan</option>{state.accounts.filter(account=>account.type !== "tarjeta_credito").map(account=><option key={account.id} value={`account:${account.id}`}>{account.name}</option>)}{state.goals.map(goal=><option key={goal.id} value={`goal:${goal.id}`}>{goal.name}</option>)}</Select></Field><Field label="Cuánto podrías utilizar"><Input type="number" min="0" step="0.01" value={draft.emergency.amount} onChange={e=>update("emergency",{...draft.emergency,amount:e.target.value})} /></Field><p className="text-xs text-ink-soft">No se suma al dinero total ni al disponible para gastar.{draft.emergency.sourceType === "goal" ? " Utilizarlo retrasaría ese plan de ahorro." : ""}</p></> : null}{draft.recordsComplete === false ? <p className="text-sm text-ochre">Puedes guardar el plan. Completa los registros en Movimientos para mejorar la confianza de la proyección.</p> : null}</> : null}
    {error ? <p role="alert" className="text-sm text-brick">{error}</p> : null}<div className="flex justify-between gap-2"><Button disabled={step === 1 || working} variant="secondary" onClick={()=>setStep(step-1)}>Atrás</Button>{step < 5 ? <Button onClick={()=>setStep(step+1)}>Siguiente</Button> : <Button disabled={working} onClick={save}>{working ? "Guardando…" : "Guardar Plan del mes"}</Button>}</div><Button variant="ghost" onClick={()=>setCategoriesOpen(true)}>Administrar categorías sin perder este formulario</Button><Modal open={categoriesOpen} onClose={()=>setCategoriesOpen(false)} title="Categorías de ingresos y gastos"><CategoryManager /></Modal>
  </div>;
}
