import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { buildEmptyState } from "../src/data/mockData.js";
import { saveMonthlyPlan, monthlyPlanStatus } from "../src/services/financial/monthlyPlan.js";
import { applySavingsOperation } from "../src/services/financial/savings.js";
test("no inventa disponible histórico usando cuotas actuales de tarjeta",()=>{const state={...buildEmptyState(),accounts:[{id:"cash",type:"efectivo",name:"Caja",balance:500},{id:"card",type:"tarjeta_credito",name:"Visa",balance:-100,minimumPayment:20}],transactions:[{id:"opening",type:"ingreso",amount:500,origin:"initial_balance",date:"2026-09-01",accountId:"cash"}]};state.monthlyPlans=[saveMonthlyPlan(state,{month:"2026-09",incomes:[],expenses:[],savings:[],recordsComplete:true,closingTarget:0,emergency:{status:"unknown"}},new Date(2026,8,16))];const result=monthlyPlanStatus(state,"2026-09",new Date(2026,9,1));assert.equal(result.closing,null);assert.equal(result.available,false);assert.equal(result.actualIncome,0);});
test("cierre conciliado conserva200 tras proteger300 de500 y no crea ingreso nuevo",()=>{let state={...buildEmptyState(),accounts:[{id:"cash",name:"Caja",type:"efectivo",balance:500}],transactions:[{id:"opening",type:"ingreso",amount:500,origin:"initial_balance",date:"2026-09-01",accountId:"cash"}],goals:[{id:"trip",name:"Viaje",current:0,target:10000,monthlyContribution:0}]};state.monthlyPlans=[saveMonthlyPlan(state,{month:"2026-09",incomes:[],expenses:[],savings:[],recordsComplete:true,closingTarget:0,emergency:{status:"unknown"}},new Date(2026,8,16))];state=applySavingsOperation(state,{goalId:"trip",accountId:"cash",amount:300,method:"protect"},()=>"saving-one",new Date(2026,8,30,12));const october=new Date(2026,9,1,12);const old=monthlyPlanStatus(state,"2026-09",october);assert.equal(old.historical,true);assert.equal(old.available,true);assert.equal(old.closing,200);assert.equal(old.cash.total,500);assert.equal(old.actualIncome,0);assert.equal(monthlyPlanStatus(state,"2026-10",october).cash.spendable,200);assert.equal(state.transactions.length,1);});
test("SQL mantiene propietario, metadatos, idempotencia y asiento de pago de tarjeta",async()=>{const planning=await readFile(new URL("../supabase/migrations/202609160001_monthly_planning.sql",import.meta.url),"utf8");const ledger=await readFile(new URL("../supabase/migrations/202609160002_card_ledger_reconciliation.sql",import.meta.url),"utf8");assert.match(planning,/enable row level security/);assert.match(planning,/with check \(\(select auth.uid\(\)\) = user_id\)/);assert.match(planning,/processed_requests/);assert.match(planning,/previous\.monthly_plans/);assert.match(ledger,/:card-entry/);assert.match(ledger,/linkedCreditCardId/);assert.match(ledger,/data_revision=p_expected_revision for update/);assert.doesNotMatch(planning+ledger,/service_role/);});
