import test from 'node:test';
import {getUpcomingCommitments,getSavingsRealized} from '../src/services/financial/calculations.js';
import assert from 'node:assert/strict';
import {buildEmptyState} from '../src/data/mockData.js';
import {financeReducer} from '../src/services/financeReducer.js';
import {migrateState} from '../src/services/migrations.js';
import {profileToday,validateMovementDate,validateMovementWrites} from '../src/services/financial/movementDates.js';
import {actualMonth,actualFinancialHealth} from '../src/services/financial/actualMonth.js';
import {ensureStandardSavings,reassignSavings} from '../src/services/financial/standardSavings.js';
import {estimateGoalCompletion} from '../src/services/financial/goals.js';
const now=new Date('2026-09-17T02:00:00Z');
function state(){return {...buildEmptyState(),profile:{timezone:'America/La_Paz',onboardingCompleted:true},accounts:[{id:'cash',type:'efectivo',name:'Efectivo',balance:1000},{id:'saving',type:'ahorro',name:'Ahorro',balance:500}],transactions:[],goals:[],savingsAllocations:[]};}
test('Bolivia conserva el día civil antes de medianoche UTC',()=>assert.equal(profileToday({},now),'2026-09-16'));
test('zona inválida usa Bolivia',()=>assert.equal(profileToday({timezone:'invalid'},now),'2026-09-16'));
test('hoy y ayer son válidos',()=>{validateMovementDate('2026-09-16',{},now);validateMovementDate('2026-09-15',{},now);});
test('mañana se rechaza',()=>assert.throws(()=>validateMovementDate('2026-09-17',{},now),/fecha futura/));
test('fecha inexistente se rechaza',()=>assert.throws(()=>validateMovementDate('2026-02-30',{},now),/válida/));
test('persistencia rechaza nuevos movimientos futuros',()=>assert.throws(()=>validateMovementWrites(null,{...state(),transactions:[{id:'f',date:'2026-09-17'}]},now),/futura/));
test('persistencia conserva registros futuros antiguos sin cambios',()=>{const s={...state(),transactions:[{id:'f',date:'2026-09-17',amount:20}]};validateMovementWrites(s,s,now);});
test('persistencia rechaza editar importe futuro',()=>{const s={...state(),transactions:[{id:'f',date:'2026-09-17',amount:20}]};assert.throws(()=>validateMovementWrites(s,{...s,transactions:[{...s.transactions[0],amount:30}]},now),/futura/);});
test('crear movimiento futuro falla antes de mutar saldo',()=>{const s=state();assert.throws(()=>financeReducer(s,{type:'ADD_TRANSACTION',payload:{date:'2099-01-01',amount:50,accountId:'cash',type:'gasto'}}),/futura/);assert.equal(s.accounts[0].balance,1000);});
test('editar movimiento futuro falla',()=>{const s={...state(),transactions:[{id:'t',date:'2026-09-01',amount:10,accountId:'cash',type:'gasto'}]};assert.throws(()=>financeReducer(s,{type:'UPDATE_TRANSACTION',payload:{id:'t',date:'2099-01-01'}}),/futura/);});
test('Ahorros no asigna una ubicación sin confirmación',()=>{const s=ensureStandardSavings(state());assert.equal(s.goals[0].current,0);assert.equal(actualMonth(s,'2026-09',now).cash.total,1500);assert.equal(s.transactions.length,0);});
test('migración de Ahorros es idempotente',()=>{const s=migrateState(state());assert.deepEqual(migrateState(s),s);});
test('Ahorros cero es válido',()=>{const s=state();s.accounts[1].balance=0;assert.equal(ensureStandardSavings(s).goals[0].current,0);});
test('reutiliza plan Ahorros equivalente',()=>{const s=state();s.goals=[{id:'old',name:'Ahorros',target:1000,current:500}];const n=ensureStandardSavings(s);assert.equal(n.goals.length,1);assert.equal(n.goals[0].id,'old');assert.equal(n.goals[0].current,500);});
test('reasignar no crea aporte, ingreso ni saldo',()=>{const s=financeReducer(ensureStandardSavings(state()),{type:'SAVE_INITIAL_SAVINGS',payload:{allocations:[{accountId:'saving',amount:500}]}});s.goals.push({id:'trip',name:'Viaje',target:1000,current:0});const n=reassignSavings(s,{goalId:'trip',accountId:'saving',amount:200,requestId:'r'});assert.equal(n.goals[0].current,300);assert.equal(n.goals[1].current,200);assert.deepEqual(n.accounts,s.accounts);assert.equal(n.savingsContributions.length,2);assert.equal(n.savingsContributions[1].method,"reassign");assert.equal(getSavingsRealized(n),0);assert.deepEqual(reassignSavings(n,{goalId:'trip',accountId:'saving',amount:200,requestId:'r'}),n);});
test('saldo inicial no es ingreso real ni semanal',()=>{const s=state();s.transactions=[{id:'i',type:'ingreso',amount:1000,date:'2026-09-01',origin:'initial_balance'}];const facts=actualMonth(s,'2026-09',now);assert.equal(facts.income,0);assert.equal(facts.weeks.reduce((sum,w)=>sum+w.income,0),0);});
test('registros futuros se excluyen de hechos y saldo disponible',()=>{const s=state();s.transactions=[{id:'f',accountId:'cash',type:'ingreso',amount:100,date:'2026-09-17'}];const facts=actualMonth(s,'2026-09',now);assert.equal(facts.income,0);assert.equal(facts.cash.spendable,1400);assert.equal(facts.futureCount,1);});
test('estimaciones no mejoran salud real',()=>{const s=state();const before=actualFinancialHealth(s,'2026-09',now);s.monthlyPlans=[{month:'2026-09',incomes:[{estimated:999999}],closingTarget:0}];assert.deepEqual(actualFinancialHealth(s,'2026-09',now),before);});
test('frecuencia semanal calcula cada siete días',()=>{const result=estimateGoalCompletion({target:1000,current:0,monthlyContribution:250,contributionFrequency:'semanal'},undefined,new Date(2026,0,31));assert.equal(result.periods,4);assert.equal(result.date.getMonth(),1);assert.equal(result.date.getDate(),28);});
test('mensual conserva ancla y limita fin de mes',()=>{const result=estimateGoalCompletion({target:200,current:0,monthlyContribution:100},undefined,new Date(2026,0,31));assert.equal(result.date.getMonth(),2);assert.equal(result.date.getDate(),31);});
test('gráficos vacíos no producen NaN ni porcentajes ficticios',()=>{const facts=actualMonth(state(),'2026-09',now);assert.deepEqual(facts.categories,[]);assert.equal(facts.result,0);assert.ok(facts.weeks.every(w=>Number.isFinite(w.income+w.expense)));});
test("aporte semanal usa cinco fechas reales en una ventana de treinta días",()=>{const s=state();s.goals=[{id:"trip",name:"Viaje",target:10000,current:0,monthlyContribution:100,contributionFrequency:"semanal"}];const items=getUpcomingCommitments(s,30,new Date(2026,8,17)).filter(item=>item.kind==="objetivo");assert.equal(items.length,5);assert.equal(items.reduce((sum,item)=>sum+item.amount,0),500);});
