import test from 'node:test';
import assert from 'node:assert/strict';
import {buildEmptyState} from '../src/data/mockData.js';
import {financeReducer as reduce} from '../src/services/financeReducer.js';
import {spendingMoney, monthlyPlanStatus} from '../src/services/financial/monthlyPlan.js';
import {goalUsed} from '../src/services/financial/savingsFunding.js';
import {goalProgress} from '../src/services/financial/goals.js';
import {migrateState} from '../src/services/migrations.js';
const now=new Date(2026,8,17,12);
function state(){return {...buildEmptyState(),profile:{onboardingCompleted:true,timezone:'America/La_Paz'},accounts:[{id:'cash',name:'Efectivo',type:'efectivo',balance:1000},{id:'bank',name:'Banco',type:'ahorro',balance:4000}],goals:[{id:'general',name:'Ahorros',system:'standard_savings',target:0,current:300},{id:'phone',name:'Celular',target:1200,current:1200}],savingsAllocations:[{goalId:'general',accountId:'cash',amount:300},{goalId:'phone',accountId:'bank',amount:1200}]};}
function expense(s,amount=1200,funded=1200,accountId='bank'){return reduce(s,{type:'ADD_TRANSACTION',payload:{id:'expense',description:'Celular',type:'gasto',category:'otros_gastos',date:'2026-09-01',accountId,amount,savingsFunding:funded ? {goalId:'phone',accountId,amount:funded,goalName:'Celular'} : null}});}
function plan(s,{expense=5000,income=6000,savings=[]}={}){return {...s,monthlyPlans:[{month:'2026-09',incomes:[{id:'income',categoryId:'sueldo',estimated:income}],expenses:[{id:'expense-plan',categoryId:'otros_gastos',classification:'variable',estimated:expense}],savings,closingTarget:0,recordsComplete:true,emergency:{status:'unknown'}}]};}
test('5000 reales, 1500 apartados y 3500 libres; el tipo ahorro no bloquea el resto',()=>assert.deepEqual(spendingMoney(state()),{total:5000,savings:1200,protectedMoney:300,spendable:3500}));
test('cuenta de ahorro sin asignación conserva todo su saldo libre',()=>{const s=state();s.savingsAllocations=[];assert.equal(spendingMoney(s).spendable,5000);});
test('plan estándar se reutiliza sin crear saldos o ubicaciones',()=>{const s=migrateState(state());assert.equal(s.goals.filter(g=>g.system==='standard_savings').length,1);assert.deepEqual(migrateState(s),s);assert.equal(spendingMoney(s).total,5000);});
test('ahorro anterior sin ubicación permanece pendiente, sin asignarse arbitrariamente',()=>{const s=state();s.savingsAllocations=[];const n=migrateState(s);assert.equal(n.goals.find(g=>g.id==='phone').needsReconciliation,true);assert.deepEqual(n.savingsAllocations,[]);assert.equal(n.goals.find(g=>g.id==='phone').current,1200);});
test('configuración inicial explícita permite cero y es idempotente',()=>{const s=state();s.goals=[];s.savingsAllocations=[];const action={type:'SAVE_INITIAL_SAVINGS',payload:{allocations:[{accountId:'cash',amount:0},{accountId:'bank',amount:0}]}};const n=reduce(s,action);assert.equal(n.goals[0].current,0);assert.equal(reduce(n,action),n);});
test('un plan puede apartar dinero en varias ubicaciones',()=>{const s=state();const n=reduce(s,{type:'SAVINGS_OPERATION',payload:{goalId:'general',accountId:'bank',method:'protect',amount:200}});assert.equal(n.savingsAllocations.filter(row=>row.goalId==='general').length,2);assert.equal(spendingMoney(n).total,5000);});
test('varios planes comparten una cuenta sin reservar el mismo dinero',()=>{const s=state();const n=reduce(s,{type:'SAVINGS_OPERATION',payload:{goalId:'general',accountId:'bank',method:'protect',amount:200}});assert.equal(spendingMoney(n).spendable,3300);});
test('reasignar entre cualquier plan cambia el propósito y no la ubicación',()=>{const n=reduce(state(),{type:'SAVINGS_OPERATION',payload:{method:'reassign',sourceGoalId:'phone',goalId:'general',accountId:'bank',amount:200}});assert.equal(n.goals.find(g=>g.id==='phone').current,1000);assert.equal(spendingMoney(n).spendable,3500);assert.equal(n.accounts[1].balance,4000);});
test('transferir dinero apartado mueve reserva y saldos una sola vez',()=>{const action={type:'SAVINGS_OPERATION',payload:{method:'move',goalId:'phone',accountId:'bank',destinationAccountId:'cash',amount:500,requestId:'move'}};const n=reduce(state(),action);assert.equal(n.accounts[0].balance,1500);assert.equal(n.accounts[1].balance,3500);assert.equal(n.savingsAllocations.find(row=>row.goalId==='phone' && row.accountId==='cash').amount,500);assert.equal(spendingMoney(n).spendable,3500);assert.equal(n.goals.find(g=>g.id==='phone').current,1200);assert.equal(reduce(n,action),n);});
test('liberar dinero lo devuelve al disponible en una cuenta de ahorro',()=>{const n=reduce(state(),{type:'SAVINGS_OPERATION',payload:{method:'release',goalId:'phone',accountId:'bank',amount:200}});assert.equal(spendingMoney(n).spendable,3700);assert.equal(n.accounts[1].balance,4000);assert.equal(goalUsed(n,'phone'),0);});
test('compra bancaria 4000/1200 deja saldo2800, reserva0 y libre2800 en esa cuenta',()=>{const n=expense(state());assert.equal(n.accounts[1].balance,2800);assert.equal(n.savingsAllocations.filter(row=>row.goalId==='phone').length,0);assert.equal(spendingMoney(n).spendable,3500);assert.equal(goalUsed(n,'phone'),1200);assert.equal(goalProgress({...n.goals.find(g=>g.id==='phone'),used:goalUsed(n,'phone')}).restante,0);});
test('gasto mixto consume solo la parte libre adicional',()=>{const n=expense(state(),1500,1200);assert.equal(spendingMoney(n).spendable,3200);assert.equal(n.accounts[1].balance,2500);});
test('editar gasto restaura la reserva anterior antes de volver a aplicarla',()=>{const n=reduce(expense(state()),{type:'UPDATE_TRANSACTION',payload:{id:'expense',amount:1000,savingsFunding:{goalId:'phone',accountId:'bank',amount:1000}}});assert.equal(n.accounts[1].balance,3000);assert.equal(n.savingsAllocations.find(row=>row.goalId==='phone').amount,200);assert.equal(goalUsed(n,'phone'),1000);});
test('eliminar gasto restaura saldo y reserva, sin avance utilizado ficticio',()=>{const n=reduce(expense(state()),{type:'DELETE_TRANSACTION',payload:'expense'});assert.equal(n.accounts[1].balance,4000);assert.equal(n.savingsAllocations.find(row=>row.goalId==='phone').amount,1200);assert.equal(goalUsed(n,'phone'),0);});
test('cambiar cuenta exige ahorros ubicados allí y conserva todo ante el fallo',()=>{const s=expense(state());const snapshot=structuredClone(s);assert.throws(()=>reduce(s,{type:'UPDATE_TRANSACTION',payload:{id:'expense',accountId:'cash',savingsFunding:{goalId:'phone',accountId:'cash',amount:1200}}}));assert.deepEqual(s,snapshot);});
test('gastar saldo protegido sin seleccionar plan se rechaza',()=>assert.throws(()=>expense(state(),3000,0),/dinero libre/));
test('no se consume más reserva que la asignada',()=>assert.throws(()=>expense(state(),1300,1300),/ahorros suficientes/));
test('no se aparta más dinero libre en la ubicación',()=>assert.throws(()=>reduce(state(),{type:'SAVINGS_OPERATION',payload:{method:'protect',goalId:'general',accountId:'bank',amount:2800.01}}),/dinero libre/));
test('proyección6000 previstos/4000 cobrados/5000 gastos =1000, nunca duplica cobros',()=>{const s=state();s.accounts=[{id:'bank',type:'ahorro',balance:4000}];s.savingsAllocations=[];s.transactions=[{id:'salary',type:'ingreso',category:'sueldo',accountId:'bank',date:'2026-09-01',amount:4000}];const r=monthlyPlanStatus(plan(s),'2026-09',now);assert.equal(r.incomePending,2000);assert.equal(r.closing,1000);});
test('los500 ya gastados disminuyen saldo y pendiente por igual: cierre1000',()=>{const s=state();s.accounts=[{id:'bank',type:'banco',balance:3500}];s.savingsAllocations=[];s.transactions=[{type:'ingreso',category:'sueldo',accountId:'bank',date:'2026-09-01',amount:4000},{type:'gasto',category:'otros_gastos',accountId:'bank',date:'2026-09-01',amount:500}];const r=monthlyPlanStatus(plan(s),'2026-09',now);assert.equal(r.variablePending,4500);assert.equal(r.closing,1000);});
test('900 previstos a tres planes dejan100 de1000 sin mutar reservas reales',()=>{const s=state();s.accounts=[{id:'bank',type:'banco',balance:1000}];s.savingsAllocations=[];const p=plan(s,{income:0,expense:0,savings:[{goalId:'phone',estimated:400},{goalId:'general',estimated:300},{goalId:'trip',estimated:200}]});assert.equal(monthlyPlanStatus(p,'2026-09',now).closing,100);assert.deepEqual(s.savingsAllocations,[]);});
test('ejecutar previsión reduce pendiente y no cambia el cierre otra vez',()=>{const s=plan(state(),{income:0,expense:0,savings:[{goalId:'general',estimated:200}]});const before=monthlyPlanStatus(s,'2026-09',now).closing;const n=reduce(s,{type:'SAVINGS_OPERATION',payload:{goalId:'general',accountId:'cash',method:'protect',amount:200,planMonth:'2026-09',requestId:'planned'}});assert.equal(monthlyPlanStatus(n,'2026-09',now).savingsPending,0);assert.equal(monthlyPlanStatus(n,'2026-09',now).closing,before);assert.equal(reduce(n,{type:'SAVINGS_OPERATION',payload:{requestId:'planned'}}),n);});
test('gasto pendiente financiado por reserva no descuenta dos veces el libre',()=>{const s=plan(state(),{income:0,expense:1200});Object.assign(s.monthlyPlans[0].expenses[0],{fundingGoalId:'phone',fundingAccountId:'bank',fundingAmount:1200});const before=monthlyPlanStatus(s,'2026-09',now);assert.equal(before.closing,3500);assert.equal(monthlyPlanStatus(expense(s),'2026-09',now).closing,3500);});
test('varios compromisos reparten un pago parcial sin marcar todos pagados',()=>{const s=plan(state(),{income:0,expense:800});s.monthlyPlans[0].expenses=[{id:'one',categoryId:'otros_gastos',classification:'fijo',estimated:400},{id:'two',categoryId:'otros_gastos',classification:'fijo',estimated:400}];s.transactions=[{type:'gasto',category:'otros_gastos',date:'2026-09-01',amount:500}];const r=monthlyPlanStatus(s,'2026-09',now);assert.equal(r.fixedPending,300);assert.equal(r.expenses.filter(row=>row.completed).length,1);assert.equal(r.actualExpense,500);});
test('vincular después un gasto no lo descuenta dos veces',()=>{const s=plan(state(),{income:0,expense:800});s.monthlyPlans[0].expenses[0].classification='fijo';s.transactions=[{id:'t',type:'gasto',category:'otros_gastos',date:'2026-09-01',amount:500}];const before=monthlyPlanStatus(s,'2026-09',now);s.transactions[0].planItemId='expense-plan';s.transactions[0].planMonth='2026-09';assert.equal(monthlyPlanStatus(s,'2026-09',now).fixedPending,before.fixedPending);});
test('excesos no vuelven negativos los pendientes ni compensan otra categoría',()=>{const s=plan(state(),{income:100,expense:100});s.transactions=[{type:'ingreso',category:'sueldo',date:'2026-09-01',amount:200},{type:'gasto',category:'otros_gastos',date:'2026-09-01',amount:200}];const r=monthlyPlanStatus(s,'2026-09',now);assert.equal(r.incomePending,0);assert.equal(r.variablePending,0);assert.equal(r.alerts[0].alert,'superado');});
test('centavos conservan precisión en saldo, reserva y consumo',()=>{const s=state();s.savingsAllocations[1].amount=1200.01;s.goals[1].current=1200.01;const n=expense(s,100.01,100.01);assert.equal(n.accounts[1].balance,3899.99);assert.equal(n.savingsAllocations.find(row=>row.goalId==='phone').amount,1100);});
test('reintento de gasto financiado no duplica el consumo',()=>{const s=state();const action={type:'ADD_TRANSACTION',payload:{description:'Celular',type:'gasto',date:'2026-09-01',accountId:'bank',amount:1200,requestId:'spend',savingsFunding:{goalId:'phone',accountId:'bank',amount:1200}}};const n=reduce(s,action);assert.equal(reduce(n,action),n);});
test('persistencia rechaza alterar la financiación de un movimiento futuro antiguo',async()=>{
 const {validateMovementWrites}=await import('../src/services/financial/movementDates.js');
 const previous={...state(),transactions:[{id:'future',type:'gasto',amount:20,accountId:'bank',date:'2099-01-01'}]};
 assert.throws(()=>validateMovementWrites(previous,{...previous,transactions:[{...previous.transactions[0],savingsFunding:{goalId:'phone',accountId:'bank',amount:20}}]},now),/futura/);
});
test('archivar conserva el gasto del objetivo y cancela su previsión pendiente',()=>{
 const s=plan(expense(state()),{income:0,expense:1200,savings:[{goalId:'phone',estimated:100}]});
 const n=reduce(s,{type:'ARCHIVE_GOAL',payload:'phone'});
 assert.equal(n.goals.find(g=>g.id==='phone').archived,true);
 assert.equal(goalUsed(n,'phone'),1200);
 assert.equal(n.monthlyPlans[0].savings[0].estimated,0);
 assert.equal(n.transactions.length,s.transactions.length);
});
test('categoría no estimada permanece en los gastos reales y reduce el saldo actual',()=>{
 const s=plan(expense(state(),100,100),{income:0,expense:0});
 s.monthlyPlans[0].expenses=[];
 const r=monthlyPlanStatus(s,'2026-09',now);
 assert.equal(r.actualExpense,100);
 assert.equal(r.closing,spendingMoney(s).spendable);
});
