-- Correct reconciliation of legacy balances and explicit card-payment entries.
-- Replaces the v2 writer retained by the planning wrapper; revision/RLS remain.
create or replace function public.apply_finance_state_v2(p_state jsonb,p_expected_revision bigint,p_operation_id text) returns jsonb language plpgsql security invoker set search_path=public as $$
declare u uuid:=auth.uid(); r jsonb; a jsonb; t jsonb; g jsonb; d jsonb; c jsonb; target bigint; actual bigint; delta bigint; linked_card text;
begin
  if u is null then raise exception 'authentication required' using errcode='28000'; end if;
  select result into r from applied_operations where user_id=u and operation_id=p_operation_id; if found then return r; end if;
  insert into profiles(user_id) values(u) on conflict do nothing;
  perform 1 from profiles where user_id=u and data_revision=p_expected_revision for update;
  if not found then raise exception 'concurrent update' using errcode='40001'; end if;
  update profiles set display_name=coalesce(p_state#>>'{profile,name}',''),primary_currency=coalesce(p_state#>>'{profile,currency}','BOB'),employment_type=coalesce(p_state#>>'{profile,employmentType}',''),estimated_income_minor=to_minor((p_state#>>'{profile,estimatedMonthlyIncome}')::numeric),onboarding_completed=coalesce((p_state#>>'{profile,onboardingCompleted}')::boolean,false),data_revision=data_revision+1,updated_at=now() where user_id=u;
  for a in select * from jsonb_array_elements(coalesce(p_state->'accounts','[]')) loop
    insert into accounts(user_id,id,name,account_type,currency,opened_on,created_at,deleted_at) values(u,a->>'id',a->>'name',a->>'type',coalesce(a->>'currency',p_state#>>'{profile,currency}'),coalesce((a->>'createdAt')::timestamptz,now())::date,coalesce((a->>'createdAt')::timestamptz,now()),null)
    on conflict(user_id,id) do update set name=excluded.name,account_type=excluded.account_type,currency=excluded.currency,updated_at=now(),deleted_at=null,version=accounts.version+1;
    if a->>'type'='tarjeta_credito' then insert into credit_cards(user_id,account_id,credit_limit_minor,statement_day,payment_day,minimum_payment_minor,annual_rate) values(u,a->>'id',case when a->>'creditLimit' is null then null else to_minor((a->>'creditLimit')::numeric) end,(a->>'statementDay')::smallint,(a->>'paymentDay')::smallint,case when a->>'minimumPayment' is null then null else to_minor((a->>'minimumPayment')::numeric) end,(a->>'rate')::numeric) on conflict(user_id,account_id) do update set credit_limit_minor=excluded.credit_limit_minor,statement_day=excluded.statement_day,payment_day=excluded.payment_day,minimum_payment_minor=excluded.minimum_payment_minor,annual_rate=excluded.annual_rate,updated_at=now(); end if;
  end loop;
  delete from credit_cards c0 where user_id=u and exists (select 1 from accounts a0 where a0.user_id=u and a0.id=c0.account_id and a0.account_type<>'tarjeta_credito');
  update accounts a0 set deleted_at=now() where user_id=u and deleted_at is null and not exists (select 1 from jsonb_array_elements(coalesce(p_state->'accounts','[]')) x where x->>'id'=a0.id);
  for t in select * from jsonb_array_elements(coalesce(p_state->'transactions','[]')) loop
    insert into transactions(user_id,id,transaction_type,description,amount_minor,currency,occurred_on,category_code,payment_method,origin,generated,account_id,recurring_id,linked_debt_id,transfer_group_id,idempotency_key,deleted_at) values(u,t->>'id',t->>'type',t->>'description',to_minor((t->>'amount')::numeric),coalesce(t->>'currency',p_state#>>'{profile,currency}'),(t->>'date')::date,t->>'category',t->>'paymentMethod',coalesce(t->>'origin','user'),coalesce((t->>'generated')::boolean,false),t->>'accountId',t->>'recurringId',t->>'linkedDebtId',t->>'transferGroupId',case when t->>'origin'='initial_balance' then 'initial:'||(t->>'accountId') else null end,null)
    on conflict(user_id,id) do update set transaction_type=excluded.transaction_type,description=excluded.description,amount_minor=excluded.amount_minor,currency=excluded.currency,occurred_on=excluded.occurred_on,category_code=excluded.category_code,payment_method=excluded.payment_method,origin=excluded.origin,generated=excluded.generated,account_id=excluded.account_id,recurring_id=excluded.recurring_id,linked_debt_id=excluded.linked_debt_id,transfer_group_id=excluded.transfer_group_id,updated_at=now(),deleted_at=null,version=transactions.version+1;
    delta:=case when t ? 'balanceDelta' then to_minor((t->>'balanceDelta')::numeric) when t->>'type'='ingreso' then to_minor((t->>'amount')::numeric) when t->>'type'='gasto' then -to_minor((t->>'amount')::numeric) else 0 end;
    insert into transaction_entries(user_id,id,transaction_id,account_id,delta_minor,currency) values(u,(t->>'id')||':entry',t->>'id',t->>'accountId',delta,coalesce(t->>'currency',p_state#>>'{profile,currency}')) on conflict(user_id,id) do update set account_id=excluded.account_id,delta_minor=excluded.delta_minor,currency=excluded.currency;
    -- A credit-card payment has a cash debit and a card credit, with one
    -- visible transaction. Editing clears/replaces the explicit counterpart.
    delete from transaction_entries where user_id=u and transaction_id=t->>'id' and id=(t->>'id')||':card-entry';
    linked_card := coalesce(t->>'linkedCreditCardId',(select value->>'linkedAccountId' from jsonb_array_elements(coalesce(p_state->'debts','[]')) where value->>'id'=t->>'linkedDebtId' limit 1),(select linked_account_id from debts where user_id=u and id=t->>'linkedDebtId'));
    if linked_card is not null and t->>'type'='gasto' then
      if linked_card=t->>'accountId' or not exists(select 1 from accounts where user_id=u and id=linked_card and account_type='tarjeta_credito' and deleted_at is null) then raise exception 'invalid card payment' using errcode='23514'; end if;
      insert into transaction_entries(user_id,id,transaction_id,account_id,delta_minor,currency) values(u,(t->>'id')||':card-entry',t->>'id',linked_card,to_minor((t->>'amount')::numeric),coalesce(t->>'currency',p_state#>>'{profile,currency}'));
    end if;
  end loop;
  update transactions t0 set deleted_at=now() where user_id=u and deleted_at is null and not exists (select 1 from jsonb_array_elements(coalesce(p_state->'transactions','[]')) x where x->>'id'=t0.id);
  -- Concilia cuentas antiguas que tenían saldo pero carecían de libro completo.
  for a in select * from jsonb_array_elements(coalesce(p_state->'accounts','[]')) loop
    target:=to_minor((a->>'balance')::numeric); select coalesce(sum(e.delta_minor),0) into actual from transaction_entries e join transactions x on x.user_id=e.user_id and x.id=e.transaction_id where e.user_id=u and e.account_id=a->>'id' and x.deleted_at is null and x.id<>((a->>'id')||'-migration-balance');
    delta:=target-actual; if delta<>0 then
      insert into transactions(user_id,id,transaction_type,description,amount_minor,currency,occurred_on,category_code,origin,generated,account_id,idempotency_key) values(u,(a->>'id')||'-migration-balance','ajuste','Ajuste de migración — '||(a->>'name'),abs(delta),coalesce(a->>'currency','BOB'),current_date,'ajuste_saldo','migration_balance',true,a->>'id','migration-balance:'||(a->>'id')) on conflict(user_id,id) do update set amount_minor=excluded.amount_minor,deleted_at=null;
      insert into transaction_entries(user_id,id,transaction_id,account_id,delta_minor,currency) values(u,(a->>'id')||'-migration-balance:entry',(a->>'id')||'-migration-balance',a->>'id',delta,coalesce(a->>'currency','BOB')) on conflict(user_id,id) do update set delta_minor=excluded.delta_minor;
    else
      update transactions set deleted_at=now() where user_id=u and id=(a->>'id')||'-migration-balance' and origin='migration_balance';
    end if;
  end loop;
  for g in select * from jsonb_array_elements(coalesce(p_state->'goals','[]')) loop insert into goals(user_id,id,name,target_minor,current_minor,currency,monthly_commitment_minor,contribution_day,target_on,deleted_at) values(u,g->>'id',g->>'name',to_minor((g->>'target')::numeric),to_minor((g->>'current')::numeric),p_state#>>'{profile,currency}',to_minor((g->>'monthlyContribution')::numeric),(g->>'contributionDay')::smallint,(g->>'targetDate')::date,null) on conflict(user_id,id) do update set name=excluded.name,target_minor=excluded.target_minor,current_minor=excluded.current_minor,monthly_commitment_minor=excluded.monthly_commitment_minor,updated_at=now(),deleted_at=null; end loop;
  update goals g0 set deleted_at=now() where user_id=u and deleted_at is null and not exists (select 1 from jsonb_array_elements(coalesce(p_state->'goals','[]')) x where x->>'id'=g0.id);
  for d in select * from jsonb_array_elements(coalesce(p_state->'debts','[]')) loop insert into debts(user_id,id,name,entity,debt_type,principal_minor,balance_minor,currency,annual_rate,installment_minor,frequency,payment_day,term_months,remaining_installments,linked_account_id,deleted_at) values(u,d->>'id',d->>'name',coalesce(d->>'entity',''),coalesce(d->>'type','otro'),to_minor((d->>'principal')::numeric),to_minor((d->>'balance')::numeric),p_state#>>'{profile,currency}',coalesce((d->>'rate')::numeric,0),to_minor((d->>'installment')::numeric),coalesce(d->>'frequency','mensual'),(d->>'paymentDay')::smallint,(d->>'termMonths')::integer,(d->>'remainingInstallments')::integer,d->>'linkedAccountId',null) on conflict(user_id,id) do update set name=excluded.name,entity=excluded.entity,balance_minor=excluded.balance_minor,annual_rate=excluded.annual_rate,installment_minor=excluded.installment_minor,payment_day=excluded.payment_day,linked_account_id=excluded.linked_account_id,updated_at=now(),deleted_at=null; end loop;
  update debts d0 set deleted_at=now() where user_id=u and deleted_at is null and not exists (select 1 from jsonb_array_elements(coalesce(p_state->'debts','[]')) x where x->>'id'=d0.id);
  for c in select value||jsonb_build_object('kind','gasto') from jsonb_array_elements(coalesce(p_state->'recurringExpenses','[]')) loop insert into recurring_transactions(user_id,id,kind,name,amount_minor,currency,category_code,account_id,frequency,day_of_month,next_occurrence_on,active,deleted_at) values(u,c->>'id','gasto',c->>'name',to_minor((c->>'amount')::numeric),p_state#>>'{profile,currency}',c->>'category',c->>'accountId',coalesce(c->>'frequency','mensual'),(c->>'dayOfMonth')::smallint,(c->>'nextDate')::date,coalesce((c->>'active')::boolean,true),null) on conflict(user_id,id) do update set kind='gasto',name=excluded.name,amount_minor=excluded.amount_minor,category_code=excluded.category_code,account_id=excluded.account_id,frequency=excluded.frequency,day_of_month=excluded.day_of_month,next_occurrence_on=excluded.next_occurrence_on,active=excluded.active,updated_at=now(),deleted_at=null; end loop;
  for c in select value||jsonb_build_object('kind','ingreso') from jsonb_array_elements(coalesce(p_state->'recurringIncomes','[]')) loop insert into recurring_transactions(user_id,id,kind,name,amount_minor,currency,category_code,account_id,frequency,day_of_month,next_occurrence_on,active,deleted_at) values(u,c->>'id','ingreso',c->>'name',to_minor((c->>'amount')::numeric),p_state#>>'{profile,currency}',c->>'category',c->>'accountId',coalesce(c->>'frequency','mensual'),(c->>'dayOfMonth')::smallint,(c->>'nextDate')::date,coalesce((c->>'active')::boolean,true),null) on conflict(user_id,id) do update set kind='ingreso',name=excluded.name,amount_minor=excluded.amount_minor,category_code=excluded.category_code,account_id=excluded.account_id,frequency=excluded.frequency,day_of_month=excluded.day_of_month,next_occurrence_on=excluded.next_occurrence_on,active=excluded.active,updated_at=now(),deleted_at=null; end loop;
  update recurring_transactions r0 set deleted_at=now() where user_id=u and deleted_at is null and not exists (select 1 from (select value from jsonb_array_elements(coalesce(p_state->'recurringExpenses','[]')) union all select value from jsonb_array_elements(coalesce(p_state->'recurringIncomes','[]'))) x where x.value->>'id'=r0.id);
  for c in select * from jsonb_array_elements(coalesce(p_state->'savingsContributions','[]')) loop insert into savings_contributions(user_id,id,kind,goal_id,amount_minor,currency,contributed_on,origin,deleted_at) values(u,c->>'id',c->>'kind',c->>'linkedGoalId',to_minor((c->>'amount')::numeric),p_state#>>'{profile,currency}',(c->>'date')::date,coalesce(c->>'origin','user'),null) on conflict(user_id,id) do update set amount_minor=excluded.amount_minor,contributed_on=excluded.contributed_on,updated_at=now(),deleted_at=null; end loop;
  update savings_contributions c0 set deleted_at=now() where user_id=u and deleted_at is null and not exists (select 1 from jsonb_array_elements(coalesce(p_state->'savingsContributions','[]')) x where x->>'id'=c0.id);
  insert into user_financial_settings(user_id,emergency_current_minor,emergency_months_target,emergency_configured,essential_expenses_configured,essential_category_ids,savings_target_type,savings_target_value,debt_status,expected_income_minor,expected_variable_expenses_minor,next_income_on,income_frequency,section_guides_seen,currency_history) values(u,to_minor((p_state#>>'{emergencyFund,current}')::numeric),coalesce((p_state#>>'{emergencyFund,monthsTarget}')::integer,3),coalesce((p_state#>>'{emergencyFund,configured}')::boolean,false),coalesce((p_state#>>'{financialSettings,essentialExpensesConfigured}')::boolean,false),array(select jsonb_array_elements_text(coalesce(p_state#>'{financialSettings,essentialCategoryIds}','[]'))),coalesce(p_state#>>'{financialSettings,savingsTargetType}','percentage'),(p_state#>>'{financialSettings,savingsTargetValue}')::numeric,coalesce(p_state#>>'{financialSettings,debtStatus}','unconfigured'),case when p_state#>>'{financialSettings,projection,expectedMonthlyIncome}' is null then null else to_minor((p_state#>>'{financialSettings,projection,expectedMonthlyIncome}')::numeric) end,case when p_state#>>'{financialSettings,projection,expectedVariableExpenses}' is null then null else to_minor((p_state#>>'{financialSettings,projection,expectedVariableExpenses}')::numeric) end,(p_state#>>'{financialSettings,projection,nextIncomeDate}')::date,coalesce(p_state#>>'{financialSettings,projection,incomeFrequency}','mensual'),coalesce(p_state->'sectionGuidesSeen','{}'),coalesce(p_state->'currencyHistory','[]')) on conflict(user_id) do update set emergency_current_minor=excluded.emergency_current_minor,emergency_months_target=excluded.emergency_months_target,emergency_configured=excluded.emergency_configured,essential_expenses_configured=excluded.essential_expenses_configured,essential_category_ids=excluded.essential_category_ids,savings_target_type=excluded.savings_target_type,savings_target_value=excluded.savings_target_value,debt_status=excluded.debt_status,expected_income_minor=excluded.expected_income_minor,expected_variable_expenses_minor=excluded.expected_variable_expenses_minor,next_income_on=excluded.next_income_on,income_frequency=excluded.income_frequency,section_guides_seen=excluded.section_guides_seen,currency_history=excluded.currency_history,updated_at=now();
  r:=get_finance_state(); insert into applied_operations(user_id,operation_id,result) values(u,p_operation_id,r); return r;
end $$;
